### ISSUE TITLE
assertion failed: self.idx % 2 == 0

### ISSUE THREAD

**Issue by rohitjoshi** [termoshtt/rust-sfmt#17]
Thanks for SIMD support for rand. See you can see [here](https://github.com/boxtown/statrs/issues/83), it outperforms other `mt` implementations.

I am using ` sfmt::thread_rng();` and  `rayon` parallel iterator.  

During benchmark test, I see randomly it throws below error which is an asset condition. I am using mac-osx.

```
thread '<unnamed>' panicked at 'assertion failed: self.idx % 2 == 0', /Users/xxxx/.cargo/registry/src/github.com-1ecc6299db9ec823/sfmt-0.2.2/src/lib.rs:56:9
test prior::tests::sigma_par_rust                  ... FAILED
```

**Comment by rohitjoshi** [comment]
I think found the problem. when `sfmt::thread_rng()` function used in `rand::distributions::WeightedChoice` and rayon's parallel iterator `into_par_iter`, it gives above error. It works fine if I use standard/sequential iterator `into_iter`.

 `rand:thread_rng()` work fine with rayon's `into_par_iter` and `rand::distributions::WeightedChoice`


```
        let mut wc = WeightedChoice::new(&mut items);
        let mut v = Vec::with_capacity(prior_conf.num_data_points);
         (0..prior_conf.num_data_points)
            .into_par_iter()
            .map(|_| {
                
                //let mut rng = rand::thread_rng();  //this work fine
                let mut rng = sfmt::thread_rng(); //this give error
                wc.ind_sample(&mut rng) as usize
            })
            .collect_into_v(&mut v);
```

If I use standard/sequential iterator,  it works fine.

```
       let mut wc = WeightedChoice::new(&mut items);
        let v = (0..prior_conf.num_data_points)
            .into_iter()
            .map(|_| {
                let mut rng = sfmt::thread_rng();
                wc.ind_sample(&mut rng) as usize
            })
            .collect();
```

**Comment by termoshtt** [comment]
> assertion failed: self.idx % 2 == 0

This assertion is in [pop64](https://github.com/termoshtt/rust-sfmt/blob/master/src/lib.rs#L56), and it happen when you get `u64` random number after a `u32`:

```
let mut rng = sfmt::SFMT::new(1234);  // seed
let r = rng.gen::<u32>();
let r = rng.gen::<u64>();
```

This is a limitation of [the original SFMT written in C](http://www.math.sci.hiroshima-u.ac.jp/~m-mat/MT/SFMT/index.html), but we can easily avoid it.
I will write a patch for this. Thanks.

**Comment by termoshtt** [comment]
Please check with new version.

**Comment by rohitjoshi** [comment]
It fixed the issue.  Thank you for the quick response. 👍
